#!/usr/bin/env bash
# Update package list and install nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get - install nginx
sudo service nginx status

# Configure nginx to listen on port 80
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx reload
