#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the
# string Ceci n'est pas une page
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\\
error_page 404 /404.html;\\
location = /404.html {\\
root /var/www/html;\\
internal;\\
}"
sudo sed -i "s#listen 80 default_server;#$new_string#" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
