#!/usr/bin/env bash
# removing the /run/nginx.pid file. The -f option in the ln command is used to forcefully remove the file if it exists
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
