#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.
# Your script should only display,user, ID, Homedirectory
path="/etc/passwd"
while read -r line
do
	echo "$line" | cut -d ":" -f-1,3,6
done < "$path"
