#!/usr/bin/env bash
# a Bash script that displays:
# The content of the current directory
# Where only the part of the name after the first dash is displayed
file=$(ls .)
for element in $file
do
	echo "$element" | cut -d - -f 2
done
